---
header-includes:
   - \usepackage{amsmath}
   - \usepackage{amsfonts}
output:
  html_document: default
---

\newcommand{\mb}[1]{\mathbf{#1}}
\newcommand{\var}{\text{var}}
\newcommand{\cov}{\text{cov}}

```{r setup-V1-P2-I1, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
set.seed(42) # NIPALS starts with a random vector
```

```{r, echo=FALSE, include=FALSE}
library(nipalsMCIA)
library(ggplot2)
library(ComplexHeatmap)
```

<!-- Loading NCI60 data and running nipals_multiblock()
    whenever running from individual Rmarkdowns -->
```{r child="Load-Shared-Vars.Rmd", include=FALSE}
```

## Part 2: Interpreting Global Loadings
In addition to the global scores matrix, MCIA also calculates a global loadings matrix $A$ that is $p\times r$.

### Pseudoeigenvalues representing the contribution of each omic to the global factor score
```{r, fig.width=4, fig.height=1.5, fig.align='center'}
## Should make into a function
bs_weights<-as.matrix(data.frame(mcia_results$block_score_weights))
colnames(bs_weights)<-c(1:10)
Heatmap(bs_weights, cluster_columns=FALSE, cluster_rows=FALSE, name = "weight",
                        column_title_side = "bottom", column_title = "Factor")
```