\documentclass{article}
\usepackage{amsmath}
\usepackage{times}
\usepackage{hyperref}
\usepackage[numbers]{natbib}
\usepackage{graphicx}

\title{Analysis of Multi-Omics Data with Multiple Co-Inertia Analysis via Nonlinear Iterative Partial Least Squares (NIPALS)}
\author{Maximilian Mattessich}

\begin{document}
\SweaveOpts{concordance=TRUE}
\maketitle

\section{Setup}
A test dataset of NCI60 cancer cell line data with 3 blocks (mRNA, proteins, and micro-RNA) is included to illustrate how the function works with multi-omics data. Installing the package can be done via the \verb+devtools+ package:
<<load_lib_data,  eval=TRUE, echo=FALSE>>=
install.packages("devtools") # required for install_github
library(devtools)

install_github("Muunraker/NIPALS-MCIA")
library(nipalsMCIA)

data(NCI60data) # loads data
@


\end{document}
