---
title: "Analysis of MCIA Decomposition"
author: "Max Mattessich, Joaquin Reyna, Anna Konstorum, Edel Aron"
date: "Compiled: `r format(Sys.time(), '%d %B %Y')`"
header-includes:
   - \usepackage{amsmath}
   - \usepackage{amsfonts}
output: 
    rmdformats::readthedown
vignette: >
  %\VignetteIndexEntry{Analysis-of-MCIA-Decomposition}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

\newcommand{\mb}[1]{\mathbf{#1}}
\newcommand{\var}{\text{var}}
\newcommand{\cov}{\text{cov}}

```{r setup-merger, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
set.seed(42) # NIPALS starts with a random vector
```

```{r, echo=FALSE, include=FALSE}
library(nipalsMCIA)
```

<!-- Including the introduction - Part 0 -->
```{r child = 'Vignette1.Analysis-of-MCIA-decomposition/Vignette1.Part0.Introduction.Rmd'}
```

<!-- Including Part 1: Deciphering/Interpreting Factor Scores -->
```{r child = 'Vignette1.Analysis-of-MCIA-decomposition/Vignette1.Part1.Item1.2D-Plots-and-Scree.Rmd'}
```

```{r child = 'Vignette1.Analysis-of-MCIA-decomposition/Vignette1.Part1.Item2.Heatmap.Rmd'}
```

<!-- Including Part 2: Deciphering/Interpreting Global Loadings --> 
```{r child = 'Vignette1.Analysis-of-MCIA-decomposition/Vignette1.Part2.Item1.Pseudoeigenvalues.Rmd'}
```

```{r child = 'Vignette1.Analysis-of-MCIA-decomposition/Vignette1.Part2.Item2.Scree.Rmd'}
```

<!--```{r child = 'Vignette1.Analysis-of-MCIA-decomposition/Vignette1.Part2.Item3.Pathway-Analysis.Rmd'}
```-->
