---
title: "Vignette 1 - Understanding the Results of MCIA"
author:
    - Max Mattessich
    - Joaquin Reyna
    - Anna Konstorum
header-includes:
   - \usepackage{amsmath}
   - \usepackage{amsfonts}
date: "9/1/2022"
output:
  pdf_document: default
  html_document: default
---

\newcommand{\mb}[1]{\mathbf{#1}}
\newcommand{\var}{\text{var}}
\newcommand{\cov}{\text{cov}}

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
set.seed(42) # NIPALS starts with a random vector
```

```{r, echo=FALSE,include=FALSE}
library(nipalsMCIA)
library(ggplot2)
library(tidyverse)
library(fgsea)
```

## Part 2: Interpreting Global Loadings
### Pathway analysis for the top factors using data from gene-centric omics blocks 

First, we compute the first 10 global factors for the dataset:
```{r,warning=FALSE,message=FALSE,fig.height=3}
data(NCI60) # this creates the dataset as `data_blocks`
mcia_results <- nipals_multiblock(data_blocks,
                                  preprocMethod='colprofile',
                                  plots = 'none',
                                  num_PCs = 10,
                                  tol=1e-12)
```

```{r, warning=FALSE}
# extra gene-centric data
mrna_gfscores <- mcia_results$global_loadings
mrna_rows = str_detect(row.names(mrna_gfscores), '_mrna')
mrna_gfscores <- mrna_gfscores[mrna_rows,]
row.names(mrna_gfscores) <- str_remove(rownames(mrna_gfscores), "_[0-9]*_.*")

# load pathway data
path.database = '../data/c2.cp.reactome.v6.2.symbols.gmt'
pathways <- fgsea::gmtPathways(path.database)

# run the comparison
geneset_report = gsea_report(mrna_gfscores, path.database,
                      factors = c(1,2,3), pval.thr = 0.05)

```

```{r}
geneset_report[[1]]
```

```{r}
geneset_report[[2]]
```