---
title: "Mini-Lecture: Brief outline of the math behind MCIA"
author:
    - Max Mattessich
    - Joaquin Reyna
    - Anna Konstorum
date: "9/1/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction
Multiple Co-Inertia Analysis (MCIA) is a joint dimensionality  reduction method which takes as input multiple datasets from the same sample but different different experimental sources. This method then calculates factors that find relationships across all data sources and the resulting matrix compositions can be used for a variety of downstream analyses.

# Theory

# Table of abbreviations
| Abbreviation | Description |
|-:|:------|
| $X$ | Dataset matrix or global data matrix (MCIA) typically in $\mathbb{R}^{n \times p}$ |
| $p$ | The number of columns/variables/features of the global data matrix |
| $n$ | The number of rows/samples/observations of the global and block data matrices | 
| $X_k$ | $k^{th}$ Data block matrix in the multi-block stucture (MCIA) | 
| $p_k$ | The number of columns/variables/features f the $h^{th}$ block data matrix | 
| $N$ | The number of blocks in the multi-block structure of $X$ | 
| $f^{(j)}$ | PC score of order $j$ (PCA) or global score of order j (MCIA) | 
| $a^{(j)}$ | PC loading of order $j$ (PCA) or global loading of order j (MCIA) |
| $f_k^{(j)}$ | Block score for block $k$ of order $j$ | 
| $a_k^{(j)}$ | Block loading for block $k$ of order $j$ | 
| $S$ or $S_X$ | Covariance matrix of dataset $X$ | 
| $T^{(j)}$ | the $n \times N$ matrix with columns consisting of the order-j block scores |
.
.
.
(tbd)

